# Generated by Django 3.2.5 on 2021-07-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='model_title',
            new_name='post_title',
        ),
    ]
